[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "langtune"
version = "0.1.0"
description = "A package for language models."
authors = [
    { name = "Pritesh Raj", email = "priteshraj41@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.8"
license = { file = "LICENSE" }
